name: snap_core20
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap20.outputs.snap }}
    steps:
    - uses: actions/checkout@v2
      with:
        # full history for latest tag name
        fetch-depth: 0
    - run: mv snap_core20 snap
    - uses: snapcore/action-build@v1
      id: build-snap20

    # Make sure the snap is installable
    - run: |
        sudo snap install --dangerous ${{ steps.build-snap20.outputs.snap }}

    - uses: actions/upload-artifact@v3
      with:
        name: plotjuggler-snap20
        path: ${{ steps.build-snap20.outputs.snap }}

  publish:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: plotjuggler-snap20
        path: .
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{needs.build.outputs.snap-file}}
        release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}
